services:
  - type: web
    name: speaking-sim-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: SPEECHACE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false